---
driver:
  name: vagrant
  customize:
   memory: 18432

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[rippled::default]
    attributes:
