name 'rippled'
maintainer 'Dmitry Grigorenko'
maintainer_email 'grigorenko.d@gmail.com'
version '0.1.0'
license          'MIT'
description      'Installs and configures a rippled node'
supports         'ubuntu 14.04'
depends 'apt'
